# Interactive graph

<style>
  * {
    font-family: sans-serif;
  }
</style> 
<div id="selectButton"></div>
<div id="plot">
</div>

<script src="https://cdn.jsdelivr.net/npm/d3@7"></script>
<script src="scripts/myscript.js"></script>

**Inferences from the graph**

The graph illustrates the statewise impact of various anti-tobacco and pro-tobacco strategies on tobacco cessation efforts in India. The X-axis displays different strategies categorized into two groups:

1. Strategies aimed at promoting tobacco cessation or discouraging its use, such as spreading health warnings, coverage in mass media, and organizing community events. These strategies are assumed to have a positive impact by increasing the percentage of tobacco users who want to quit.

2. Strategies that appear to promote tobacco use, such as tobacco advertisements and promotions, typically employed by tobacco companies. These may have a negative impact by potentially decreasing the percentage of tobacco users who want to quit.

The height of each bar indicates the level of influence or the extent to which each strategy is employed within the states. For example, a taller bar for "Health Warnings" suggests a higher percentage of anti-tobacco messaging impact in that particular state.

The first bar represents the number of tobacco smokers who plan on quitting. Comparing these figures to the anti and pro-tobacco strategies shows their impact on the decisions of people living in those areas. A higher percentage of people who want to quit helps us understand what is working effectively in a state, while a lower number indicates what isn't the need for further strategy implementation and curbing advertisements in those areas.

The key takeaway from this graph is to compare the extent to which anti-tobacco strategies are implemented and effective against pro-tobacco strategies within states. Policymakers and public health officials can use this data to assess the current landscape of tobacco control efforts and plan future public health campaigns. It can also help identify areas where additional resources might be required to combat the influence of tobacco advertising and promotions. Additionally, this analysis can be further refined by considering the urban and rural demographics to tailor policies more effectively
